---
title: "R Notebook"
output: html_notebook
---

## Trajectory
```{r}
library(monocle)
library(dplyr)
library(Seurat)
library(RColorBrewer)

rm(list=ls())
setwd("~/Desktop/Xinyu_Patchseq/")
load("./neuron_monkey.rda")
```

```{r}
seu.1=readRDS("./human_query.rds")
seu.1 = seu.1[,seu.1$predicted.celltype=="Neuron"]
e.human=e.human[colnames(seu.1),]
seu.1=seu.1[,e.human$`Days in vitro (DIV)`== 0]
```
### 1 Monkey neurons
### 2 Monkey neurons (Nutrite == "Yes")
#### 2.2 For non-cultured cells 
```{r}
# 1 load filtered dataset from seurat object
seu.0=seu[,e.monkey$`Neurite?`=="Yes" &e.monkey$`Days in vitro (DIV)`== 0]
seu.0=NormalizeData(seu.0)
seu.0=FindVariableFeatures(seu.0,nfeatures = 2000)
seu.0=ScaleData(seu.0)
seu.0 <- RunPCA(seu.0, npcs = 30, verbose = FALSE)
seu.0 <- RunUMAP(seu.0, reduction = "pca", dims = 1:30)

mat.0 = as.matrix(seu.0@assays$RNA@counts[VariableFeatures(seu.0),])
barcodes = colnames(seu.0)
features = data.frame(row.names=VariableFeatures(seu.0))
group = e.monkey[barcodes,]$PCD
Gestation = factor(e.monkey[barcodes,]$`Gestation Day (GD)`)
meta.0 = data.frame(barcodes, group, Gestation)
pd <- new("AnnotatedDataFrame", data = meta.0)
fd <- new("AnnotatedDataFrame", data = features)
fd$gene_short_name = VariableFeatures(seu.0)
colnames(mat.0) = rownames(barcodes)
rownames(mat.0) = rownames(features)
## create monocle object
mono_obj.0 <- newCellDataSet(as(mat.0,  "sparseMatrix"),
                           phenoData = pd, 
                           featureData = fd,
                           expressionFamily=negbinomial())

# calculate basic summary statistics of the expressino data
mono_obj.0 <- estimateSizeFactors(mono_obj.0)
mono_obj.0 <- estimateDispersions(mono_obj.0)

mono_obj.0 <- detectGenes(mono_obj.0, min_expr = 1)

diff_test_res.0 <- differentialGeneTest(mono_obj.0, fullModelFormulaStr = "~Gestation")
ordering_genes <- row.names(subset(diff_test_res.0, qval < 0.5))
```

```{r}
#genes = intersect(rownames(seu.0),rownames(seu.1))
genes = intersect(rownames(seu.1),ordering_genes)
mat.m = as.matrix(seu.0@assays$RNA@counts[genes,])
mat.h = as.matrix(seu.1@assays$RNA@counts[genes,])
mat = cbind(mat.m,mat.h)
barcodes = colnames(mat)
features = data.frame(row.names=genes)
group = c(rep("monkey",dim(mat.m)[2]),rep("human",dim(mat.h)[2]))
Gestation = factor(c(e.monkey[colnames(mat.m),]$`Gestation Day (GD)`,e.human[colnames(mat.h),]$`Gestation Day (GD)`),
                   levels = c(90,96,100,106,112,155,132))
meta = data.frame(barcodes, group,Gestation)
pd <- new("AnnotatedDataFrame", data = meta)
fd <- new("AnnotatedDataFrame", data = features)
fd$gene_short_name = genes
colnames(mat) = rownames(barcodes)
rownames(mat) = rownames(features)
## create monocle object
mono_obj <- newCellDataSet(as(mat,  "sparseMatrix"),
                           phenoData = pd, 
                           featureData = fd,
                           expressionFamily=negbinomial())

# calculate basic summary statistics of the expressino data
mono_obj <- estimateSizeFactors(mono_obj)
mono_obj <- estimateDispersions(mono_obj)

mono_obj <- detectGenes(mono_obj, min_expr = 1)

#diff_test_res <- differentialGeneTest(mono_obj, fullModelFormulaStr = "~Gestation")
diff_test_res <-differentialGeneTest(mono_obj, fullModelFormulaStr = " ~ Gestation + group", reducedModelFormulaStr = " ~ Gestation")

ordering_genes <- row.names(subset(diff_test_res, qval < 0.05))

mono_obj <- setOrderingFilter(mono_obj, ordering_genes)

mono_obj <- reduceDimension(mono_obj, max_components = 2, method = 'DDRTree')
mono_obj <- orderCells(mono_obj)

Gestation_col = c("#E4EFF6","#AFCFE5","#79B0D3","#4490C2","#29709E","#1E5478","#CB4335")

plot_cell_trajectory(mono_obj, color_by = "Gestation",cell_size = 3,show_tree = FALSE,show_branch_points = FALSE) + scale_color_manual(values=Gestation_col)
```

```{r}
tt = CreateSeuratObject(mat)
tt=AddMetaData(tt,group,"group")
tt=AddMetaData(tt,Gestation,"gestation")
tt.list = SplitObject(tt, split.by = "group")
tt.list = lapply(X=tt.list, function(x){x = NormalizeData(x);x=FindVariableFeatures(x)})
features = SelectIntegrationFeatures(tt.list)
anchors=FindIntegrationAnchors(object.list=tt.list,anchor.features=features,dims = 1:10,k.score = 10,k.filter = 10)
combined = IntegrateData(anchorset = anchors,k.weight = 10)
DefaultAssay(combined)="integrated"
combined=ScaleData(combined)
combined=RunPCA(combined)
DimPlot(combined)
DimPlot(combined,group.by = "group")
DimPlot(combined,group.by = "gestation")
combined=RunUMAP(combined,reduction = "pca",dims=1:30)
DimPlot(combined)
DimPlot(combined,group.by = "group")
DimPlot(combined,group.by = "gestation")
   
sce=as.SingleCellExperiment(combined)
assays(sce)$norm=combined@assays$integrated@scale.data
sce = slingshot(sce,clusterLabels = "gestation", reducedDim="UMAP")

library(grDevices)
colors <- colorRampPalette(brewer.pal(11,'Spectral')[-6])(100)
plotcol <- colors[cut(sce$slingPseudotime_1, breaks=100)]

plot(reducedDims(sce)$UMAP, col = plotcol, pch=16, asp = 1)
lines(SlingshotDataSet(sce), lwd=2, col='black')
plot(reducedDims(sce)$UMAP, col = plotcol, pch=16, asp = 1)

plotcol <- colors[cut(sce$slingPseudotime_2, breaks=100)]
plot(reducedDims(sce)$UMAP, col = plotcol, pch=16, asp = 1)

plotcol <- colors[cut(sce$slingPseudotime_3, breaks=100)]
plot(reducedDims(sce)$UMAP, col = plotcol, pch=16, asp = 1)

```
